### ISSUE TITLE
@skeema/firestore beta release roadmap

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/skeema#4]
### Overview

`@skeema/firestore` makes managing your models in Firestore easy and provides first-class TypeScript support. 

Building on the brilliant runtime type checking from ([io-ts](https://github.com/gcanti/io-ts)) there are a number of important data management extras that can be provided fairly cheaply.

Outlined here is what I feel it will take before this library becomes ready to be considered for `beta` usage.

<br>

#### Code

- [x] Support for defining typechecked schema
- [x] Typed support for model instance methods 
- [x] Typed support for static schema methods
- [ ] `io-ts` utilities for crafting codecs and custom types
- [x] [DEFAULT] Transaction based updates
- [ ] [DEFAULT] Validation of schema models with configuration option to switch it off
- [ ] Option for non transaction based updates
- [ ] Query support for finding multiple models
- [ ] Batch support for creating multiple models at once
- [ ] Enable option for non transactional updates
- [ ] Perform queries on multiple items of data ⬆
- [ ] Add support for document [references](https://stackoverflow.com/a/47673346)
- [ ] Add support for nested collection references
- [ ] Add support for GeoData fields
- [ ] Relationships between models and data population
- [ ] Test coverage > 90%

#### Documentation

- [x] Getting started documentation
- [x] Roadmap to beta
- [ ] Contributing guidelines
- [ ] Docusaurus site with in depth documentation
